### ISSUE TITLE
Posts/comments/likes and dislikes

### ISSUE THREAD

**Issue by leed85** [UNLV-CS472-672/2024-F-GROUP3-RebelHub#2]
Addition of posting functionality, tied to account. Posts will have image, description, ability to comment to from other users, and likes and dislikes

**Comment by barrioskevin** [comment]
I am closing this issue since posts has already been integrated to the main repo. if you are still working on something regarding "posts/comments/likes and dislikes" then let's make sure that we open a new issue that's *specific* to what you plan on targeting.
