### ISSUE TITLE
No current CI

### ISSUE THREAD

**Issue by barrioskevin** [UNLV-CS472-672/2024-F-GROUP3-RebelHub#27]
---
name: CI Workflow
about: Setting up github actions to properly build and test our project on merges/pull requests
title: CI
labels: 'github actions'
assignees: @imawful 

---

**Description of the issue**
We have previously had troubles when merging new changes into the project. Due to some typos, after changes were merged into the master branch we were unable to build and run the project. Of course it was only a small issue since we just needed to fix some typos but I think we need a way to make sure our project will always build and run successfully after each merge. I'm suggesting a CI workflow similar to the assignment that we had in class about setting up github actions.

**Files that need to be updated**
`.github/workflows/workflow.yml`
`backend/Posts/tests.py`
`backend/hubs/tests.py`

**Link**
Include a link to the correlated PR number, or any resources for greater context.
[https://docs.github.com/en/actions/writing-workflows](url)
[https://johnxu21.github.io/teaching/CS472/Timetable/CI/?](url)

**Additional context**
We will need to make sure that any tests we write/have written still pass before each pr/merge

**Comment by thecatfour** [comment]
This was solved with #28
