### ISSUE TITLE
Profile page Backend

### ISSUE THREAD

**Issue by leed85** [UNLV-CS472-672/2024-F-GROUP3-RebelHub#49]
**Description of the issue**
Backend for the profile page (i.e. update profile, buttons routing, and getting potst/archives)

**Files that need to be updated**
Frontend: update profile.css and profile.js to work with backend
backend: new file: profile.py

**Link**
[Update when pull request is created*
](https://github.com/UNLV-CS472-672/2024-F-GROUP3-RebelHub/pull/80)

**Screenshots/Example (Optional)**
[update when pull request is created*
](https://github.com/UNLV-CS472-672/2024-F-GROUP3-RebelHub/pull/80)

**Additional context**
[update when pull request is created*
](https://github.com/UNLV-CS472-672/2024-F-GROUP3-RebelHub/pull/80)

**Comment by leed85** [comment]
Will update with more detailed descriptions when pull request is created

**Comment by thecatfour** [comment]
Closed with #80
