### ISSUE TITLE
Home Page Frontend

### ISSUE THREAD

**Issue by leed85** [UNLV-CS472-672/2024-F-GROUP3-RebelHub#50]
**Description of the issue**
Homepage frontend. Design of the main page a user would access immediately after entering the page when logged in

**Files that need to be updated**
Frontend: `frontend/src/app/page.js`

**Link**
Update when added*

**Screenshots/Example (Optional)**
Update when added*

**Additional context**
Just the frontend for the homepage

**Comment by thecatfour** [comment]
Closed with #92
