### ISSUE TITLE
Overlapping sidebar and navbar. Only one should have a logo.

### ISSUE THREAD

**Issue by nnguyen144** [UNLV-CS472-672/2024-F-GROUP3-RebelHub#73]
**Description of the issue**
The sidebar and navbar both have logos, which isn't necessary. I believe that the logo for the sidebar can be removed but there are different ways to implement this. 

**Files that need to be updated**
frontend\src\components\navbar\RebelHubNavBar.js
frontend\src\components\navbar\RebelHubNavBar.module.css
frontend\src\components\sidebar.css
frontend\src\components\sidebar.js

**Comment by leed85** [comment]
I updated this and will be in my pull request later this week
