### ISSUE TITLE
Image/Thumbnail for posts

### ISSUE THREAD

**Issue by thecatfour** [UNLV-CS472-672/2024-F-GROUP3-RebelHub#77]
**Description of the issue**
Posts are supposed to have an image/thumbnail to help illustrate their message.

**Files that need to be updated**

- Posts/models.py: Will need an image field.
- Posts/tests.py: Will need tests for when there is/isn't an image.
- Posts/serializers.py: Will need to link the image somehow.
- src/components/posts/post-summary.tsx: Will need to display the image in a small format.
- src/components/posts/post-summary-detailed.tsx: Will need to display the full image.
- src/components/posts/forms/...: Forms related to posts will need to include input for an image.

**Link**
Include a link to the correlated PR number, or any resources for greater context.

**Screenshots/Example (Optional)**
Posts currently have a placeholder to represent where an image would go. These should be replaced by any PR that intends on addressing this issue.

**Additional context**
Since images may be more difficult to check for offensive content, we may need a report feature in the future.

**Comment by leed85** [comment]
I added a PIctures Model for posts, on profile final pull request https://github.com/UNLV-CS472-672/2024-F-GROUP3-RebelHub/pull/80 need to just incorporate it with posts
